---
- hosts: all
  user: yaquino
  gather_facts: no
 
  tasks:
    - name: Check if nmap file is set
      lineinfile: 
        path: /etc/facter/facts.d/ha_nmap.txt
        line: 'nmap=enable'
        state: present
      check_mode: yes
