---
- hosts: all
  user: yasser
  gather_facts: no
  tasks:
     - name: Check that the file resolv.conf exists
       stat:
         path: /etc/resolv.conf
       register: p
     - debug:
         msg: "File exists..."
       when: p.stat.exists
     - debug:
         msg: "File not found"
       when: p.stat.exists == False
